name: Build and push container image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag
      id: vars
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build image
      # for now we assume that every new tag is the latest
      run: docker build -t ghcr.io/${{ github.repository_owner }}/bird:${{ env.TAG }} -t ghcr.io/${{ github.repository_owner }}/bird:latest .

    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/bird --all-tags
